[package]
name = "reth-revm-inspectors"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "revm inspector implementations used by reth"

[dependencies]
# reth 
reth-primitives = { path = "../../primitives" }
reth-rpc-types = { path = "../../rpc/rpc-types" }

revm = { workspace = true }
# remove from reth and reexport from revm
hashbrown = "0.13"

# misc
serde = { version = "1.0", features = ["derive"] }
thiserror = {version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }

# js-tracing-inspector
boa_engine = { git = "https://github.com/boa-dev/boa", optional = true }
boa_runtime = { git = "https://github.com/boa-dev/boa", optional = true }

[features]
js-tracer = ["boa_engine", "boa_runtime", "thiserror", "serde_json"]